package com.hibernate.HQL;

// default package
// Generated Sep 21, 2015 12:46:49 PM by Hibernate Tools 4.3.1

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private Integer empId;
	private String addressLine1;
	private Integer zipcode;

	public Address() {
	}

	public Address(String addressLine1, Integer zipcode) {
		this.addressLine1 = addressLine1;
		this.zipcode = zipcode;
	}

	public Integer getEmpId() {
		return this.empId;
	}

	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public Integer getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(Integer zipcode) {
		this.zipcode = zipcode;
	}

}
